services:
  - type: web
    name: elegance-fashion
    env: node
    plan: free
    buildCommand: npm install && NODE_ENV=production npm run build
    startCommand: npm start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BASE_URL
        value: https://elegance-fashion.onrender.com
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    autoDeploy: true
    healthCheckPath: /
    domains:
      - elegance-fashion.onrender.com 